baseurl = "https://bg2bkk.github.io"
languageCode = ""
title = "BG2BKK Site"
#paginate = 10
hasCJKLanguage = false
DefaultContentLanguage = "en"
disqusShortname= "hugo-theme-stack"

[pagination]
  pagerSize = 5

[caches]
  [caches.images]
    dir = ':cacheDir/images'
